# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/server_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerWindow(object):
    def setupUi(self, ServerWindow):
        ServerWindow.setObjectName("ServerWindow")
        ServerWindow.resize(604, 555)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(9)
        ServerWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ServerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 581, 391))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelMessages = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelMessages.setObjectName("labelMessages")
        self.verticalLayout_2.addWidget(self.labelMessages)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 400, 581, 20))
        self.line_2.setAutoFillBackground(False)
        self.line_2.setLineWidth(0)
        self.line_2.setMidLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.labelCN = QtWidgets.QLabel(self.centralwidget)
        self.labelCN.setGeometry(QtCore.QRect(10, 430, 581, 20))
        self.labelCN.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCN.setObjectName("labelCN")
        self.labelRollNo = QtWidgets.QLabel(self.centralwidget)
        self.labelRollNo.setGeometry(QtCore.QRect(10, 460, 581, 20))
        self.labelRollNo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRollNo.setObjectName("labelRollNo")
        ServerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ServerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        ServerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ServerWindow)
        self.statusbar.setObjectName("statusbar")
        ServerWindow.setStatusBar(self.statusbar)
        self.actionChange_Port = QtWidgets.QAction(ServerWindow)
        self.actionChange_Port.setObjectName("actionChange_Port")
        self.actionQuit = QtWidgets.QAction(ServerWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionStart_Server = QtWidgets.QAction(ServerWindow)
        self.actionStart_Server.setObjectName("actionStart_Server")
        self.menuMenu.addAction(self.actionChange_Port)
        self.menuMenu.addAction(self.actionStart_Server)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(ServerWindow)
        QtCore.QMetaObject.connectSlotsByName(ServerWindow)

        return self.labelMessages, self.scrollArea

    def retranslateUi(self, ServerWindow):
        _translate = QtCore.QCoreApplication.translate
        ServerWindow.setWindowTitle(_translate("ServerWindow", "Server"))
        self.labelMessages.setText(_translate("ServerWindow", "<html><head/><body></body></html>"))
        self.labelCN.setText(_translate("ServerWindow", "Computer Networks Special Assignment"))
        self.labelRollNo.setText(_translate("ServerWindow", "Bhavya Patel (20BEC018), Vatsal Gajjar (20BEC035)"))
        self.menuMenu.setTitle(_translate("ServerWindow", "Menu"))
        self.actionChange_Port.setText(_translate("ServerWindow", "Set Port"))
        self.actionQuit.setText(_translate("ServerWindow", "Quit"))
        self.actionStart_Server.setText(_translate("ServerWindow", "Start Server"))
